Add SignIn, NotFound
HsiaooooooJu/simple-twitter pull request #6
Opened 2022-10-04 17:53 UTC by HsiaooooooJu

我太雷了＝＝完全忘記要分兩個 signIn，我後來改成 views > AdminSignIn.vue、views > UserSignIn、components > SignInForm，重新推了一次～

2022-10-04 17:57 UTC, HsiaooooooJu commented
加油加油～～～

2022-10-05 02:33 UTC, ConnieSheep requested changes
1. 登入頁面密碼沒有隱藏
2. 路由下次記得需要修改
3. AdminSignIn script coding style 請修改

2022-10-05 02:39 UTC, HsiaooooooJu commented
1. 在 input 加上 type="password" 成功隱藏了～
2. 好
3. 改好了～

2022-10-05 03:10 UTC, ConnieSheep approved these changes
審核通過 ~
下次 PR 請修改 input 的字體大小與間距 !

2022-10-05 03:14 UTC, merged